"""
Daily Summary para Client Follow-Up Autopilot.
Genera y envía reportes de actividad diaria al equipo CS vía email y Slack.
Incluye: items procesados, emails enviados/borradores, respuestas de clientes, métricas de aprendizaje.

Funciones:
  - send_daily_summary(): Resumen general por email + Slack
  - send_eod_slack_summary(): Resumen de seguimientos realizados al final de la jornada (Slack solamente)
"""

import json
import logging
from datetime import datetime, timezone, timedelta
from pathlib import Path

import gmail_client
import notion_client
import slack_client
import team_manager
from config import (
    GMAIL_DEFAULT_SENDER_EMAIL,
    SLACK_REVIEW_CHANNEL,
    SYSTEM_MODE,
    COMPANY_NAME,
    STYLE_DATA_DIR,
)
from style_store import load_metrics

logger = logging.getLogger(__name__)


def _count_items_by_status():
    """Count Notion items by status."""
    try:
        pages = notion_client.query_database()
        counts = {}
        for page in pages:
            status = notion_client.get_status_property(page, "Status") or "Unknown"
            counts[status] = counts.get(status, 0) + 1
        return counts, len(pages)
    except Exception as e:
        logger.error(f"Error counting items: {e}")
        return {}, 0


def generate_summary():
    """
    Generate a daily summary report.

    Returns:
        Dict with 'subject', 'body_html', 'body_text'
    """
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")

    # Get Notion status counts
    status_counts, total_items = _count_items_by_status()

    # Get learning metrics
    metrics = load_metrics()

    # Build summary
    subject = f"Follow-Up Autopilot — Daily Summary ({date_str})"

    # Status breakdown
    status_rows = ""
    for status in ["Sin empezar", "En curso", "Listo"]:
        count = status_counts.get(status, 0)
        if count > 0:
            status_rows += f"<tr><td>{status}</td><td><strong>{count}</strong></td></tr>"

    # Learning metrics
    approval_rate = metrics.get("approval_rate", 0)
    approval_pct = f"{approval_rate:.0%}" if approval_rate else "N/A"
    total_drafts = metrics.get("total_drafts", 0)
    sent_as_is = metrics.get("sent_as_is", 0)
    sent_edited = metrics.get("sent_edited", 0)
    discarded = metrics.get("discarded", 0)

    body_html = f"""
    <h2>📊 Follow-Up Autopilot — Daily Summary</h2>
    <p><strong>Date:</strong> {date_str} | <strong>Mode:</strong> {SYSTEM_MODE}</p>

    <h3>📋 Item Status Overview</h3>
    <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;">
        <tr style="background:#f0f0f0;"><th>Status</th><th>Count</th></tr>
        {status_rows}
        <tr style="background:#f0f0f0;"><td><strong>Total</strong></td><td><strong>{total_items}</strong></td></tr>
    </table>

    <h3>🤖 Learning Metrics</h3>
    <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;">
        <tr><td>Total drafts processed</td><td><strong>{total_drafts}</strong></td></tr>
        <tr><td>Sent as-is (no edits)</td><td><strong>{sent_as_is}</strong></td></tr>
        <tr><td>Sent with edits</td><td><strong>{sent_edited}</strong></td></tr>
        <tr><td>Discarded</td><td><strong>{discarded}</strong></td></tr>
        <tr><td>Approval rate</td><td><strong>{approval_pct}</strong></td></tr>
    </table>

    <h3>ℹ️ System Info</h3>
    <ul>
        <li><strong>Current Mode:</strong> {SYSTEM_MODE}</li>
        <li><strong>Mode Criteria:</strong> DRAFT → SEMI_AUTO at 80% approval | SEMI_AUTO → AUTO at 95% approval</li>
    </ul>

    <p style="color:#888; font-size:12px;">Generated by {COMPANY_NAME} Follow-Up Autopilot</p>
    """

    body_text = f"""Follow-Up Autopilot — Daily Summary ({date_str})
Mode: {SYSTEM_MODE}
Total items: {total_items}
Status: {json.dumps(status_counts)}
Drafts processed: {total_drafts} | Approval rate: {approval_pct}
"""

    return {
        "subject": subject,
        "body_html": body_html,
        "body_text": body_text,
    }


def send_daily_summary():
    """Generate and send the daily summary via email and Slack."""
    summary = generate_summary()

    # Send via email to all team members
    recipients = team_manager.get_daily_summary_recipients()
    for email_addr in recipients:
        email_result = gmail_client.send_email(
            to=email_addr,
            subject=summary["subject"],
            body_html=summary["body_html"],
            from_email=GMAIL_DEFAULT_SENDER_EMAIL,
        )
        if email_result:
            logger.info(f"Daily summary sent to {email_addr}")
        else:
            logger.error(f"Failed to send daily summary to {email_addr}")

    # Send via Slack
    if SLACK_REVIEW_CHANNEL:
        slack_client.send_message(
            channel_id=SLACK_REVIEW_CHANNEL,
            text=summary["body_text"],
            blocks=[
                {
                    "type": "header",
                    "text": {"type": "plain_text", "text": f"📊 Daily Summary — {datetime.now().strftime('%Y-%m-%d')}", "emoji": True}
                },
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": summary["body_text"]}
                },
            ]
        )
        logger.info("Daily summary posted to Slack")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print("Generando resumen diario...\n")
    summary = generate_summary()
    print(summary["body_text"])


# ═════════════════════════════════════════════════════════════════════════════
# RESUMEN DE FIN DE JORNADA (5 PM Perú) — Solo Slack
# ═════════════════════════════════════════════════════════════════════════════

def _get_today_followups():
    """
    Obtiene los seguimientos realizados hoy desde el log de drafts y el log de Notion.

    Returns:
        Lista de dicts con info de cada seguimiento del día
    """
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    followups = []

    # 1. Leer drafts_log.jsonl del día
    drafts_log = STYLE_DATA_DIR / "drafts_log.jsonl"
    if drafts_log.exists():
        try:
            with open(drafts_log, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entry = json.loads(line)
                        ts = entry.get("timestamp", "")
                        if ts.startswith(today_str):
                            followups.append({
                                "proyecto": entry.get("project_name", "—"),
                                "cliente": entry.get("client_name", "—"),
                                "etapa": entry.get("stage", "?"),
                                "idioma": entry.get("language", "?"),
                                "asunto": entry.get("subject", "—"),
                                "destinatario": entry.get("to", "—"),
                                "modo": entry.get("status", SYSTEM_MODE),
                                "draft_id": entry.get("draft_id", ""),
                                "hora": ts[11:16] if len(ts) > 16 else "—",
                            })
                    except json.JSONDecodeError:
                        continue
        except Exception as e:
            logger.warning(f"Error leyendo drafts_log.jsonl: {e}")

    # 2. Complementar con Notion: buscar items con Last Follow-Up Date = hoy
    try:
        pages = notion_client.query_database()
        for page in pages:
            last_fu = notion_client.get_date_property(page, "Last Follow-Up Date")
            if last_fu == today_str:
                proj = notion_client.resolve_project_name(page)
                stage = notion_client.get_number_property(page, "Follow-Up Stage")
                # Evitar duplicados con drafts_log
                already = any(f["proyecto"] == proj and f["etapa"] == stage for f in followups)
                if not already:
                    followups.append({
                        "proyecto": proj or notion_client.get_text_property(page, "Nombre"),
                        "cliente": notion_client.resolve_client_name(page) or "—",
                        "etapa": stage,
                        "idioma": notion_client.get_select_property(page, "Client Language") or "—",
                        "asunto": "—",
                        "destinatario": "—",
                        "modo": SYSTEM_MODE,
                        "draft_id": "",
                        "hora": "—",
                    })
    except Exception as e:
        logger.warning(f"Error consultando Notion para resumen EOD: {e}")

    return followups


def _build_eod_blocks(followups):
    """
    Construye los bloques de Slack Block Kit para el resumen de fin de jornada.

    Args:
        followups: Lista de seguimientos del día

    Returns:
        Tuple de (blocks, fallback_text)
    """
    now = datetime.now(timezone.utc)
    date_display = now.strftime("%d/%m/%Y")
    total = len(followups)

    # Contadores por etapa
    by_stage = {}
    for fu in followups:
        s = fu["etapa"]
        by_stage[s] = by_stage.get(s, 0) + 1

    stage_names = {
        1: "📩 Recordatorio inicial",
        2: "📨 Segundo aviso",
        3: "🚨 Urgente",
        4: "🔴 Escalamiento",
    }

    # Header
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"📊 Resumen de Seguimientos — {date_display}", "emoji": True}
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"Se realizaron *{total} seguimiento{'s' if total != 1 else ''}* hoy | Modo: *{SYSTEM_MODE}*"}
        },
        {"type": "divider"},
    ]

    # Resumen por etapa
    if by_stage:
        stage_lines = []
        for stage_num in sorted(by_stage.keys()):
            name = stage_names.get(stage_num, f"Etapa {stage_num}")
            count = by_stage[stage_num]
            stage_lines.append(f"{name}: *{count}*")

        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": "*Desglose por etapa:*\n" + "\n".join(stage_lines)}
        })
        blocks.append({"type": "divider"})

    # Detalle de cada seguimiento (max 15 para no saturar Slack)
    shown = followups[:15]
    for fu in shown:
        stage_emoji = {1: "📩", 2: "📨", 3: "🚨", 4: "🔴"}.get(fu["etapa"], "📧")
        lang_flag = {"ES": "🇪🇸", "EN": "🇺🇸", "PT": "🇧🇷"}.get(fu["idioma"], "🌐")

        fields = [
            {"type": "mrkdwn", "text": f"*Proyecto:*\n{fu['proyecto']}"},
            {"type": "mrkdwn", "text": f"*Cliente:*\n{fu['cliente']}"},
            {"type": "mrkdwn", "text": f"*Etapa:*\n{stage_emoji} {fu['etapa']}"},
            {"type": "mrkdwn", "text": f"*Idioma:*\n{lang_flag} {fu['idioma']}"},
        ]

        blocks.append({"type": "section", "fields": fields})

        if fu.get("asunto") and fu["asunto"] != "—":
            blocks.append({
                "type": "context",
                "elements": [{"type": "mrkdwn", "text": f"📋 _{fu['asunto']}_"}]
            })

    if len(followups) > 15:
        blocks.append({
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": f"_...y {len(followups) - 15} seguimiento(s) más._"}]
        })

    # Sin seguimientos
    if total == 0:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": "✅ No se realizaron seguimientos hoy. Todos los pendientes están al día o fuera de horario laboral."}
        })

    # Footer
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"🤖 Generado por {COMPANY_NAME} Follow-Up Autopilot | {now.strftime('%H:%M UTC')}"}
        ]
    })

    fallback = f"Resumen de seguimientos ({date_display}): {total} seguimientos realizados hoy."
    return blocks, fallback


def send_eod_slack_summary():
    """
    Envía al canal de Slack un resumen de todos los seguimientos realizados durante el día.
    Diseñado para ejecutarse a las 5 PM hora Perú (22:00 UTC).

    Returns:
        Dict con resultado del envío o None
    """
    if not SLACK_REVIEW_CHANNEL:
        logger.warning("SLACK_REVIEW_CHANNEL no configurado. No se puede enviar resumen EOD.")
        return None

    logger.info("Generando resumen de fin de jornada...")

    followups = _get_today_followups()
    blocks, fallback_text = _build_eod_blocks(followups)

    result = slack_client.send_message(
        channel_id=SLACK_REVIEW_CHANNEL,
        text=fallback_text,
        blocks=blocks,
    )

    if result:
        logger.info(f"Resumen EOD enviado a Slack: {len(followups)} seguimientos")
    else:
        logger.error("Error enviando resumen EOD a Slack")

    return result
